/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PriceHistoryInput = IDL.Record({
  'itemId' : IDL.Nat,
  'source' : IDL.Text,
  'updatedBy' : IDL.Text,
  'itemName' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PriceHistoryEntry = IDL.Record({
  'itemId' : IDL.Nat,
  'source' : IDL.Text,
  'updatedBy' : IDL.Text,
  'timestamp' : IDL.Int,
  'itemName' : IDL.Text,
  'price' : IDL.Float64,
});
export const BaselineResult = IDL.Record({
  'method' : IDL.Text,
  'baseline' : IDL.Float64,
  'volatility' : IDL.Float64,
  'dataPoints' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GrowingClaim = IDL.Record({
  'itemId' : IDL.Nat,
  'claimedAt' : IDL.Int,
  'claimedBy' : IDL.Principal,
  'itemName' : IDL.Text,
  'landSize' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
});
export const PriceEntry = IDL.Record({
  'itemId' : IDL.Nat,
  'lastUpdatedAt' : IDL.Int,
  'updatedBy' : IDL.Principal,
  'itemName' : IDL.Text,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPriceHistory' : IDL.Func([IDL.Vec(PriceHistoryInput)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAll' : IDL.Func([], [], []),
  'clearPrice' : IDL.Func([IDL.Nat], [], []),
  'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAllPriceHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PriceHistoryEntry)],
      ['query'],
    ),
  'getAttributions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getBaseline' : IDL.Func([IDL.Nat], [BaselineResult], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClaims' : IDL.Func([], [IDL.Vec(GrowingClaim)], ['query']),
  'getMyClaims' : IDL.Func([], [IDL.Vec(GrowingClaim)], ['query']),
  'getPriceHistory' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(PriceHistoryEntry)],
      ['query'],
    ),
  'getPrices' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, PriceEntry))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeClaim' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setClaim' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'setPrice' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PriceHistoryInput = IDL.Record({
    'itemId' : IDL.Nat,
    'source' : IDL.Text,
    'updatedBy' : IDL.Text,
    'itemName' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PriceHistoryEntry = IDL.Record({
    'itemId' : IDL.Nat,
    'source' : IDL.Text,
    'updatedBy' : IDL.Text,
    'timestamp' : IDL.Int,
    'itemName' : IDL.Text,
    'price' : IDL.Float64,
  });
  const BaselineResult = IDL.Record({
    'method' : IDL.Text,
    'baseline' : IDL.Float64,
    'volatility' : IDL.Float64,
    'dataPoints' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GrowingClaim = IDL.Record({
    'itemId' : IDL.Nat,
    'claimedAt' : IDL.Int,
    'claimedBy' : IDL.Principal,
    'itemName' : IDL.Text,
    'landSize' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
  });
  const PriceEntry = IDL.Record({
    'itemId' : IDL.Nat,
    'lastUpdatedAt' : IDL.Int,
    'updatedBy' : IDL.Principal,
    'itemName' : IDL.Text,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPriceHistory' : IDL.Func([IDL.Vec(PriceHistoryInput)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAll' : IDL.Func([], [], []),
    'clearPrice' : IDL.Func([IDL.Nat], [], []),
    'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getAllPriceHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PriceHistoryEntry)],
        ['query'],
      ),
    'getAttributions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getBaseline' : IDL.Func([IDL.Nat], [BaselineResult], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClaims' : IDL.Func([], [IDL.Vec(GrowingClaim)], ['query']),
    'getMyClaims' : IDL.Func([], [IDL.Vec(GrowingClaim)], ['query']),
    'getPriceHistory' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(PriceHistoryEntry)],
        ['query'],
      ),
    'getPrices' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, PriceEntry))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeClaim' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setClaim' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'setPrice' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };